// Integrity tests for the `cortical-networks` view.
//
// The centroids in parcels.json are generated by
// scripts/derive-parcel-centroids.mjs from the fsaverage DK pial meshes. They
// are committed rather than computed at runtime (the renderer has no mesh
// parser and the OBJs are 70 files), so the one real risk is drift: someone
// nudges a number in the JSON, or edits a spec in the script, and the two stop
// agreeing. The first test here re-runs the script and compares.

import { describe, it, expect } from 'vitest';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { loadParcelRegistry } from '../../src/lib/brain-viz/parcel-registry.js';
import { loadView } from '../../src/lib/brain-viz/view-loader.js';
import { createViewContent } from '../../src/lib/brain-viz/content.js';

import parcelsRaw from '../../src/components/brain-3d/data/registry/parcels.json';
import papersRaw from '../../src/components/brain-3d/data/registry/papers.json';
import viewConfig from '../../src/components/brain-3d/data/views/cortical-networks.json';
import contentConfig from '../../src/components/brain-3d/data/content/cortical-networks.json';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');

const registry = loadParcelRegistry(parcelsRaw);
const resolved = loadView({ viewConfig, registry, papersRaw });

const cnIds = Object.keys(parcelsRaw).filter((id) => id.startsWith('cn.'));

// An overlay contributes a synthetic membership per home network
// (`deepreading::tom`) so borrowed parcels glow in the colour they already had.
// Tests about which real networks a parcel belongs to must ignore those.
const isChannel = (id) => id.includes('::');
const homeNetworks = (parcel) => parcel.networks.filter((n) => !isChannel(n));
const overlayIds = Object.entries(viewConfig.networks)
  .filter(([, def]) => def.overlay)
  .map(([id]) => id);

describe('derived centroids stay in sync with the mesh', () => {
  it('every cn.* centroid matches scripts/derive-parcel-centroids.mjs', () => {
    const out = execFileSync(
      process.execPath,
      [path.join(ROOT, 'scripts/derive-parcel-centroids.mjs'), '--json'],
      { encoding: 'utf8', maxBuffer: 1024 * 1024 * 32 },
    );
    const derived = JSON.parse(out);

    // Same set of IDs on both sides — catches a parcel added to one and not
    // the other, in either direction.
    expect(Object.keys(derived).sort()).toEqual(cnIds.sort());

    for (const [id, entry] of Object.entries(derived)) {
      expect(parcelsRaw[id].centroid, `${id} centroid`).toEqual(entry.centroid);
    }
  });

  it('records the derivation for every cn.* parcel', () => {
    for (const id of cnIds) {
      expect(parcelsRaw[id].derivation, `${id} derivation`).toBeTruthy();
    }
  });

  it('marks subcortical parcels as approximate in both provenance and derivation', () => {
    // Hippocampus and amygdala have no DK surface label, so they are offset
    // from a neighbour. That has to stay visible to a reader.
    const anchored = cnIds.filter((id) => parcelsRaw[id].provenance === 'dk-anchored');
    expect(anchored.sort()).toEqual(
      ['cn.Amyg-L', 'cn.Amyg-R', 'cn.Hipp-L', 'cn.Hipp-R'],
    );
    for (const id of anchored) {
      expect(parcelsRaw[id].derivation).toMatch(/approximate/);
      expect(parcelsRaw[id].note).toMatch(/[Aa]pproximate/);
    }
  });

  it('never stores a Talairach coordinate in the MNI field', () => {
    // Kanwisher 1997 reports Talairach; Fedorenko, Sammler and Seeley report
    // MNI. They differ by more than a centimetre in places, so the two fields
    // are kept separate and each names its source explicitly.
    for (const id of cnIds) {
      const p = parcelsRaw[id];
      if (p.mniPeak) {
        expect(p.mniPeakSource, `${id} mniPeak needs a source`).toBeTruthy();
        expect(p.mniPeakSource, `${id} mniPeak is labelled Talairach`)
          .not.toMatch(/talairach/i);
      }
      if (p.talairachPeak) {
        expect(p.talairachPeakSource, `${id} talairachPeak needs a source`).toBeTruthy();
        expect(p.mniPeak, `${id} must not carry both coordinate spaces`).toBeUndefined();
      }
    }
  });

  it('keeps every centroid inside the normalized mesh bounds', () => {
    for (const id of cnIds) {
      for (const v of parcelsRaw[id].centroid) {
        expect(Math.abs(v), `${id} component out of range`).toBeLessThanOrEqual(1.0);
      }
    }
  });
});

describe('parcels land where the anatomy says they should', () => {
  // The renderer frame is x = right, y = superior, z = anterior. These are
  // relative checks rather than absolute coordinates: they encode facts about
  // the brain that must survive any retuning of the label slices, and they
  // catch the failure mode a screenshot cannot — a region that looks plausible
  // in one camera angle but sits on the wrong side of a neighbour.
  const at = (id) => {
    const p = parcelsRaw[id];
    if (!p) throw new Error(`no such parcel ${id}`);
    return { x: p.centroid[0], y: p.centroid[1], z: p.centroid[2] };
  };

  it('puts every lateralised parcel in its own hemisphere', () => {
    for (const id of cnIds) {
      const { hemisphere, centroid } = parcelsRaw[id];
      if (hemisphere === 'L') expect(centroid[0], `${id} should be left`).toBeLessThan(0);
      if (hemisphere === 'R') expect(centroid[0], `${id} should be right`).toBeGreaterThan(0);
      if (hemisphere === 'M') expect(Math.abs(centroid[0]), `${id} should be near midline`).toBeLessThan(0.1);
    }
  });

  it('orders the language network front to back', () => {
    // Frontal fROIs sit anterior to the temporal ones, and the angular gyrus
    // is the most posterior member.
    expect(at('cn.IFG-L').z).toBeGreaterThan(at('cn.MidPostTemp-L').z);
    expect(at('cn.AntTemp-L').z).toBeGreaterThan(at('cn.PostTemp-L').z);
    expect(at('cn.MidPostTemp-L').z).toBeGreaterThan(at('cn.PostTemp-L').z);
    expect(at('cn.AngG-L').z).toBeLessThan(at('cn.IFG-L').z);
    // IFGorb is the ventral member of the frontal trio, MFG the dorsal one.
    expect(at('cn.IFGorb-L').y).toBeLessThan(at('cn.IFG-L').y);
    expect(at('cn.MFG-L').y).toBeGreaterThan(at('cn.IFG-L').y);
  });

  it('stacks the medial prefrontal regions dorsal to ventral', () => {
    expect(at('cn.dMPFC-L').y).toBeGreaterThan(at('cn.vMPFC').y);
    expect(at('cn.dACC').y).toBeGreaterThan(at('cn.sgACC').y);
  });

  it('places the motor strip correctly relative to somatosensory and articulatory cortex', () => {
    // Precentral is anterior to postcentral across the central sulcus...
    expect(at('cn.M1-L').z).toBeGreaterThan(at('cn.S1-L').z);
    // ...and the articulatory face area is the ventral end of the same strip.
    expect(at('cn.artic-L').y).toBeLessThan(at('cn.M1-L').y);
    // SMA sits on the midline, superior, and anterior to primary motor cortex.
    expect(Math.abs(at('cn.SMA').x)).toBeLessThan(0.1);
    expect(at('cn.SMA').y).toBeGreaterThan(at('cn.M1-L').y);
  });

  it('keeps the medial temporal structures in their real arrangement', () => {
    // The amygdala sits anterior and superior to the hippocampus, which is the
    // relationship the anchor offsets exist to reproduce. If a future edit to
    // those offsets breaks this, the figure is lying about the anatomy.
    for (const h of ['L', 'R']) {
      expect(at(`cn.Amyg-${h}`).z, `amygdala ${h} anterior to hippocampus`)
        .toBeGreaterThan(at(`cn.Hipp-${h}`).z);
      expect(at(`cn.Amyg-${h}`).y, `amygdala ${h} superior to entorhinal`)
        .toBeGreaterThan(at(`cn.EntC-${h}`).y);
      // Both are deep — well inside the lateral surface.
      expect(Math.abs(at(`cn.Amyg-${h}`).x)).toBeLessThan(0.35);
      expect(Math.abs(at(`cn.Hipp-${h}`).x)).toBeLessThan(0.35);
    }
    // Entorhinal is the anterior end of the parahippocampal strip.
    expect(at('cn.EntC-L').z).toBeGreaterThan(at('cn.PHC-L').z);
  });

  it('separates the MD network from its language neighbours by more than a radius', () => {
    // The figure's central claim is proximity WITHOUT overlap. Two spheres
    // closer than the sum of their radii read as one blob and assert the
    // opposite, so this is the test that keeps the drawing honest. MD's
    // opercular IFG was dropped from the view for failing exactly this check.
    const dist = (a, b) => Math.hypot(
      ...[0, 1, 2].map((i) => parcelsRaw[a].centroid[i] - parcelsRaw[b].centroid[i]),
    );
    const pairs = [
      ['cn.MD-MFG-L', 'cn.MFG-L'],
      ['cn.MD-InfPar-L', 'cn.AngG-L'],
      ['cn.MD-InfPar-L', 'cn.TPJ-L'],
      // Sammler's premotor node vs primary motor cortex on the same strip.
      ['cn.PMC-R', 'cn.M1-R'],
      // Music-selective plana sit on the supratemporal plane; the language and
      // prosody temporal parcels sit on the lateral surface of the same gyrus.
      // Left planum polare needed the tightest slice to clear cn.AntTemp-L.
      ['cn.PP-L', 'cn.AntTemp-L'],
      ['cn.PP-R', 'cn.STG-R'],
      ['cn.PT-L', 'cn.pSTS-L'],
      // Right superior temporal cortex now holds five parcels from four networks.
      ['cn.aSTS-R', 'cn.PP-R'],
      ['cn.aSTS-R', 'cn.STG-R'],
    ];
    for (const [a, b] of pairs) {
      const gap = dist(a, b);
      const radii = parcelsRaw[a].radius + parcelsRaw[b].radius;
      expect(gap, `${a} and ${b} are ${gap.toFixed(3)} apart, radii sum ${radii}`)
        .toBeGreaterThan(radii);
    }
    // And MD is bilateral where the language network is left-lateralised: it
    // has a right-hemisphere parcel for every left one.
    const mdIds = viewConfig.networks.md.parcels.filter((p) => p.startsWith('cn.MD-'));
    const left = mdIds.filter((p) => p.endsWith('-L')).map((p) => p.slice(0, -2));
    const right = mdIds.filter((p) => p.endsWith('-R')).map((p) => p.slice(0, -2));
    expect(left.sort()).toEqual(right.sort());
  });

  it('puts the ventral visual regions below the lateral temporal ones', () => {
    expect(at('cn.FFA-R').y).toBeLessThan(at('cn.pSTS-R').y);
    expect(at('cn.FFA-L').y).toBeLessThan(at('cn.pSTS-L').y);
    // The occipital face area is posterior to the fusiform one.
    expect(at('cn.OFA-R').z).toBeLessThan(at('cn.FFA-R').z);
  });

  it('keeps the insula deep and the prosody regions on the right surface', () => {
    // Anterior insula is buried, so it must sit well inside the lateral surface
    // of the superior temporal gyrus above it.
    expect(Math.abs(at('cn.AI-R').x)).toBeLessThan(Math.abs(at('cn.STG-R').x));
    expect(Math.abs(at('cn.AI-L').x)).toBeLessThan(Math.abs(at('cn.MidPostTemp-L').x));
    // Heschl's gyrus is medial to the lateral STG surface, and posterior to it.
    expect(Math.abs(at('cn.HG-R').x)).toBeLessThan(Math.abs(at('cn.STG-R').x));
    // The right prosody STS is posterior to the right STG.
    expect(at('cn.STS-R').z).toBeLessThan(at('cn.STG-R').z);
  });

  it('places the posteromedial regions behind and above the ventral memory ones', () => {
    expect(at('cn.PC-L').z).toBeLessThan(at('cn.vMPFC').z);
    expect(at('cn.PC-L').y).toBeGreaterThan(at('cn.RSC').y);
    expect(at('cn.RSC').z).toBeLessThan(at('cn.dACC').z);
  });
});

describe('cortical-networks view resolves', () => {
  it('loads all ten networks plus the overlay in declared order', () => {
    expect(resolved.networkOrder).toEqual([
      'deepreading', 'reading', 'language', 'md', 'tom', 'prosody', 'music',
      'face', 'motor', 'salience', 'episodic',
    ]);
  });

  it('resolves every parcel reference and every paper reference', () => {
    // loadView throws on an unknown parcel or paper, so reaching here is most
    // of the assertion; this pins the counts so a silent drop is caught too.
    expect(Object.keys(resolved.parcels)).toHaveLength(51);
    expect(resolved.papers).toHaveLength(viewConfig.papers.length);
  });

  it('passes displayNum, source and evidence through to the shells', () => {
    for (const id of resolved.networkOrder) {
      const net = resolved.networks[id];
      expect(net.displayNum, `${id} displayNum`).toBeTruthy();
      expect(net.source, `${id} source`).toBeTruthy();
      expect(['read', 'partial', 'background']).toContain(net.evidence);
    }
  });

  it('reports no hand-tuned networks — this view is entirely mesh-derived', () => {
    expect(resolved.provenanceFlags.handTunedNetworks).toEqual([]);
    expect(resolved.provenanceFlags.allHandTuned).toBe(false);
  });

  it('shares the parcels that belong to two networks rather than duplicating them', () => {
    // A shared parcel is what makes the renderer blend both network colors.
    // Duplicating it under two IDs would stack two spheres and hide the overlap.
    const shared = {
      'cn.IFG-R': ['language', 'prosody'],
      'cn.vMPFC': ['episodic', 'tom'],
      'cn.PC-L': ['episodic', 'tom'],
      'cn.PC-R': ['episodic', 'tom'],
      'cn.AngG-L': ['episodic', 'language'],
      'cn.SMA': ['md', 'motor'],
      'cn.dACC': ['md', 'salience'],
    };
    for (const [pid, nets] of Object.entries(shared)) {
      expect(homeNetworks(resolved.parcels[pid]), pid).toEqual(nets);
    }
  });

  it('places no two parcels at the same point', () => {
    const seen = new Map();
    for (const [id, p] of Object.entries(resolved.parcels)) {
      const key = p.centroid.join(',');
      expect(seen.get(key), `${id} collides with ${seen.get(key)}`).toBeUndefined();
      seen.set(key, id);
    }
  });
});

describe('provenance claims stay honest', () => {
  it('tags every paper this view cites with an access level', () => {
    for (const paper of resolved.papers) {
      expect(['PRIMARY-FULL', 'PRIMARY-PARTIAL', 'SECONDARY-ONLY', 'UNVERIFIED'], paper.id)
        .toContain(papersRaw[paper.id].access);
    }
  });

  it('derives each network evidence tier from its weakest citation', () => {
    // The tier must never be hand-declared — that is how a network ends up
    // showing a strong badge while citing something nobody opened. Recompute
    // it here independently of view-loader and require agreement.
    const TIER = {
      'PRIMARY-FULL': 'read',
      'PRIMARY-PARTIAL': 'partial',
      'SECONDARY-ONLY': 'partial',
      'UNVERIFIED': 'background',
    };
    const RANK = { read: 3, partial: 2, background: 1 };
    for (const id of resolved.networkOrder) {
      const ids = viewConfig.networks[id].paperIds;
      expect(ids?.length, `${id} must list its paperIds`).toBeGreaterThan(0);
      const worst = ids
        .map((pid) => TIER[papersRaw[pid]?.access] ?? 'background')
        .reduce((a, b) => (RANK[b] < RANK[a] ? b : a), 'read');
      expect(resolved.networks[id].evidence, `${id} tier`).toBe(worst);
    }
    // No hand-declared evidence may survive in the view config.
    for (const net of Object.values(viewConfig.networks)) {
      expect(net.evidence, 'evidence must be computed, not declared').toBeUndefined();
    }
  });

  it('cites no paper the networks do not actually use', () => {
    const cited = new Set(
      resolved.networkOrder.flatMap((id) => viewConfig.networks[id].paperIds),
    );
    expect([...cited].sort()).toEqual([...viewConfig.papers].sort());
  });

  // Sources that were read cover to cover but are deliberately NOT tagged
  // PRIMARY-FULL, because the tag records what kind of source something is and
  // not whether anyone opened it. Keep this list tiny and always say why.
  const READ_BUT_NOT_PRIMARY = {
    'wolf-2018': 'Trade book. Letters Two and Three read in full; it is the source for the deep-reading construct and reports no imaging of its own, so its neural claims are second-hand by construction. Retagging it PRIMARY-FULL to make this test pass would be a lie about the evidence, and would silently promote the overlay from partial to read.',
  };

  it('cites nothing that has not been read in full', () => {
    // Reached 2026-08-05 after every cited paper was obtained and read. This
    // guards the property rather than assuming it: adding a citation that is
    // abstract-only or reference-list-only will fail here, which is the moment
    // to either read it or accept the network dropping to 'partial'.
    const unread = viewConfig.papers.filter(
      (id) => papersRaw[id]?.access !== 'PRIMARY-FULL' && !READ_BUT_NOT_PRIMARY[id],
    );
    expect(unread, `not read in full: ${unread.join(', ')}`).toEqual([]);
  });

  it('documents every citation that is exempt from the read-in-full rule', () => {
    // The exemption list may not rot into a place to hide unread sources.
    for (const [id, why] of Object.entries(READ_BUT_NOT_PRIMARY)) {
      expect(viewConfig.papers, `${id} is exempted but not cited`).toContain(id);
      expect(why.length, `${id} needs a real reason`).toBeGreaterThan(80);
      expect(papersRaw[id].note, `${id} must carry its scope limits`).toBeTruthy();
    }
  });

  it('keeps the tiers honest about what was actually read', () => {
    const tiers = Object.fromEntries(
      resolved.networkOrder.map((id) => [id, resolved.networks[id].evidence]),
    );
    // Nothing may sit at 'background' — that tier means an unverified source,
    // and the whole point of the verification pass was to clear it.
    expect(Object.entries(tiers).filter(([, t]) => t === 'background')).toEqual([]);
    // Every network is at 'read'. The deep-reading overlay is not, and must not
    // be: it cites Wolf, whose account of the anatomy is a synthesis of other
    // people's imaging. A capacity nobody has localised should not wear the
    // same badge as one measured with a localiser contrast.
    const notRead = Object.entries(tiers).filter(([, t]) => t !== 'read').map(([id]) => id);
    expect(notRead, JSON.stringify(tiers)).toEqual(['deepreading']);
    expect(tiers.deepreading).toBe('partial');
  });

  it('gives every network panel copy', () => {
    const content = createViewContent(contentConfig);
    for (const id of resolved.networkOrder) {
      const entry = content.forNetwork(id);
      expect(entry.tag, `${id} tag`).toBeTruthy();
      expect(entry.whatItDoes.length, `${id} whatItDoes`).toBeGreaterThan(0);
      expect(entry.whatLightsUp.length, `${id} whatLightsUp`).toBeGreaterThan(0);
      expect(entry.sources.length, `${id} sources`).toBeGreaterThan(0);
    }
  });

  it('only writes overlap copy for pairs that actually share a parcel or are argued about', () => {
    const content = createViewContent(contentConfig);
    // Every declared overlap key must name two real networks, in the
    // alphabetical order content.js builds its lookup key with. A key written
    // the other way round resolves to nothing and the copy silently never
    // renders — which is exactly how five of these shipped broken the first time.
    for (const key of Object.keys(contentConfig.overlaps)) {
      const [a, b] = key.split('+');
      expect(resolved.networks[a], `overlap ${key}`).toBeDefined();
      expect(resolved.networks[b], `overlap ${key}`).toBeDefined();
      expect([a, b], `overlap key "${key}" is not in canonical order`).toEqual([a, b].sort());
    }
    // And the pairs that share a parcel must all have copy, so a real overlap
    // never renders unexplained.
    const sharing = new Set();
    for (const p of Object.values(resolved.parcels)) {
      // Real memberships only. A borrowed parcel trivially "shares" itself with
      // the overlay channel that borrowed it, which is plumbing, not an overlap.
      const nets = homeNetworks(p);
      for (let i = 0; i < nets.length; i++) {
        for (let j = i + 1; j < nets.length; j++) {
          sharing.add([nets[i], nets[j]].sort().join('+'));
        }
      }
    }
    for (const key of sharing) {
      expect(content.overlap(key.split('+')), `missing overlap copy for ${key}`).toBeTruthy();
    }
  });

  it('explains the overlay against every network it borrows from', () => {
    // Lighting the overlay next to one of its donors is the main way a reader
    // will use this chip, so each of those pairs needs copy.
    const content = createViewContent(contentConfig);
    for (const overlayId of overlayIds) {
      for (const homeId of resolved.networks[overlayId].borrowsFrom) {
        expect(
          content.overlap([overlayId, homeId]),
          `missing overlap copy for ${overlayId} + ${homeId}`,
        ).toBeTruthy();
      }
    }
  });
});

describe('the deep-reading overlay borrows rather than owns', () => {
  const overlay = resolved.networks.deepreading;

  it('is marked as an overlay and declares no parcels of its own', () => {
    expect(overlay.overlay).toBe(true);
    expect(viewConfig.networks.deepreading.parcels).toBeUndefined();
  });

  it('owns no parcel that is not already a member of a real network', () => {
    // The claim the whole chip makes. If this ever fails, the overlay has
    // acquired tissue of its own and stopped being an overlay.
    for (const pid of overlay.parcelIds) {
      expect(homeNetworks(resolved.parcels[pid]).length, `${pid} has no home network`)
        .toBeGreaterThan(0);
    }
  });

  it('never gets a colour of its own in the renderer palette', () => {
    // The chip carries a neutral hex for its own styling, but no parcel may
    // ever be painted with it — borrowed regions keep their home colour.
    const colors = resolved.networkColors();
    expect(colors.deepreading).toBeUndefined();
    for (const homeId of overlay.borrowsFrom) {
      expect(colors[`deepreading::${homeId}`]).toEqual(resolved.networks[homeId].rgb);
    }
  });

  it('expands to its channels for the renderer and leaves other ids alone', () => {
    const expanded = resolved.expandActive(['deepreading', 'music']);
    expect(expanded).toContain('music');
    expect(expanded).not.toContain('deepreading');
    for (const homeId of overlay.borrowsFrom) {
      expect(expanded).toContain(`deepreading::${homeId}`);
    }
    expect(resolved.expandActive(['language', 'tom'])).toEqual(['language', 'tom']);
  });

  it('leaves the fusiform face area unlit', () => {
    // Deliberate: literacy pushes face responses OUT of the left fusiform
    // (Dehaene 2014), so the FFA is what reading displaces, not what it
    // recruits. Adding it here would invert the finding.
    expect(overlay.parcelIds).not.toContain('cn.FFA-L');
    expect(overlay.parcelIds).toContain('cn.VWFA-L');
  });

  it('keeps the word form area clear of its fusiform neighbour', () => {
    const d = Math.hypot(
      ...parcelsRaw['cn.VWFA-L'].centroid.map((v, i) => v - parcelsRaw['cn.FFA-L'].centroid[i]),
    );
    const need = parcelsRaw['cn.VWFA-L'].radius + parcelsRaw['cn.FFA-L'].radius;
    expect(d, `VWFA/FFA separation ${d.toFixed(3)} vs ${need}`).toBeGreaterThan(need);
  });

  it('places the word form area posterior, lateral and superior to the FFA', () => {
    // All three relations are reported in the literature the parcel cites;
    // a future retune of the fusiform slices must not quietly break them.
    const v = parcelsRaw['cn.VWFA-L'].centroid;
    const f = parcelsRaw['cn.FFA-L'].centroid;
    expect(v[2], 'VWFA posterior to FFA').toBeLessThan(f[2]);
    expect(v[0], 'VWFA lateral to FFA').toBeLessThan(f[0]);
    expect(v[1], 'VWFA superior to FFA').toBeGreaterThan(f[1]);
  });
});
